[ 2025-10-26 18:04:09,983 ] root - INFO - Data saved to ./Datas/raw
[ 2025-10-27 13:07:17,541 ] root - INFO - Raw data loaded successfully
[ 2025-10-27 13:07:17,542 ] root - INFO - preprocessing the data 
[ 2025-10-27 13:07:17,542 ] root - INFO - Starting the preprocessing Step
[ 2025-10-27 13:07:17,545 ] root - INFO - Starting up with the train test split 
[ 2025-10-27 13:07:17,547 ] root - INFO - Done with the splitting 
[ 2025-10-27 13:07:17,547 ] root - INFO - Starting with the scaling 
[ 2025-10-27 13:07:17,549 ] root - INFO - Done with the scailing  
[ 2025-10-27 13:07:17,549 ] root - INFO - X_train_scaled shape : (1760, 7) and X_test_scaled (1760, 7)
[ 2025-10-27 13:07:17,550 ] root - INFO - Converting the trained array into dataframe
[ 2025-10-27 13:07:17,550 ] root - INFO - Converting the test array into dataframe
[ 2025-10-27 13:07:17,550 ] root - INFO - 
Preprocessing completed successfully!
[ 2025-10-27 13:07:17,550 ] root - INFO - saving the preprocessing csv's 
[ 2025-10-27 13:07:17,570 ] root - INFO - Processed train and test data saved successfully in /Users/arpitgupta/Desktop/MLOPS+LLMOPS/MLOPS-LLMOPS/Datas/processed
[ 2025-10-27 13:41:12,086 ] root - INFO - Data loaded from /Users/arpitgupta/Desktop/MLOPS+LLMOPS/MLOPS-LLMOPS/Datas/processed/train_preprocessed.csv
[ 2025-10-27 13:41:12,089 ] root - INFO - training the model 
[ 2025-10-27 13:41:12,089 ] root - ERROR - Error during model training: RandomForestClassifier.__init__() takes from 1 to 2 positional arguments but 5 were given
[ 2025-10-27 13:41:12,089 ] root - ERROR - Failed to complete the model building process: RandomForestClassifier.__init__() takes from 1 to 2 positional arguments but 5 were given
[ 2025-10-27 13:41:45,707 ] root - INFO - Data loaded from /Users/arpitgupta/Desktop/MLOPS+LLMOPS/MLOPS-LLMOPS/Datas/processed/train_preprocessed.csv
[ 2025-10-27 13:41:45,709 ] root - INFO - training the model 
[ 2025-10-27 13:41:45,709 ] root - ERROR - Error during model training: RandomForestClassifier.__init__() takes from 1 to 2 positional arguments but 3 were given
[ 2025-10-27 13:41:45,709 ] root - ERROR - Failed to complete the model building process: RandomForestClassifier.__init__() takes from 1 to 2 positional arguments but 3 were given
[ 2025-10-27 13:42:33,686 ] root - INFO - Data loaded from /Users/arpitgupta/Desktop/MLOPS+LLMOPS/MLOPS-LLMOPS/Datas/processed/train_preprocessed.csv
[ 2025-10-27 13:42:33,689 ] root - INFO - training the model 
[ 2025-10-27 13:42:33,689 ] root - ERROR - Error during model training: RandomForestClassifier.__init__() got an unexpected keyword argument 'n_estimator'
[ 2025-10-27 13:42:33,689 ] root - ERROR - Failed to complete the model building process: RandomForestClassifier.__init__() got an unexpected keyword argument 'n_estimator'
[ 2025-10-27 13:42:49,759 ] root - INFO - Data loaded from /Users/arpitgupta/Desktop/MLOPS+LLMOPS/MLOPS-LLMOPS/Datas/processed/train_preprocessed.csv
[ 2025-10-27 13:42:49,761 ] root - INFO - training the model 
[ 2025-10-27 13:42:50,021 ] root - INFO - Model training completed
[ 2025-10-27 13:42:50,026 ] root - INFO - Model saved to models/model.pkl
[ 2025-10-27 13:59:53,650 ] httpx - INFO - HTTP Request: GET https://dagshub.com/api/v1/user "HTTP/1.1 200 OK"
[ 2025-10-27 13:59:53,660 ] dagshub - INFO - Accessing as thearpitgupta2003
[ 2025-10-27 13:59:55,284 ] httpx - INFO - HTTP Request: GET https://dagshub.com/api/v1/repos/thearpitgupta2003/MLOPS-LLMOPS "HTTP/1.1 200 OK"
[ 2025-10-27 13:59:57,156 ] httpx - INFO - HTTP Request: GET https://dagshub.com/api/v1/user "HTTP/1.1 200 OK"
[ 2025-10-27 13:59:57,160 ] dagshub - INFO - Initialized MLflow to track repo "thearpitgupta2003/MLOPS-LLMOPS"
[ 2025-10-27 13:59:57,162 ] dagshub - INFO - Repository thearpitgupta2003/MLOPS-LLMOPS initialized!
[ 2025-10-27 13:59:57,734 ] root - INFO - Model loaded from ./models/model.pkl
[ 2025-10-27 13:59:57,736 ] root - ERROR - Unexpected error occurred while loading the data: [Errno 2] No such file or directory: './data/processed/test_final.csv'
[ 2025-10-27 13:59:57,736 ] root - ERROR - Failed to complete the model evaluation process: [Errno 2] No such file or directory: './data/processed/test_final.csv'
[ 2025-10-27 14:00:42,837 ] httpx - INFO - HTTP Request: GET https://dagshub.com/api/v1/user "HTTP/1.1 200 OK"
[ 2025-10-27 14:00:42,849 ] dagshub - INFO - Accessing as thearpitgupta2003
[ 2025-10-27 14:00:45,441 ] httpx - INFO - HTTP Request: GET https://dagshub.com/api/v1/repos/thearpitgupta2003/MLOPS-LLMOPS "HTTP/1.1 200 OK"
[ 2025-10-27 14:00:47,583 ] httpx - INFO - HTTP Request: GET https://dagshub.com/api/v1/user "HTTP/1.1 200 OK"
[ 2025-10-27 14:00:47,587 ] dagshub - INFO - Initialized MLflow to track repo "thearpitgupta2003/MLOPS-LLMOPS"
[ 2025-10-27 14:00:47,588 ] dagshub - INFO - Repository thearpitgupta2003/MLOPS-LLMOPS initialized!
[ 2025-10-27 14:00:48,020 ] root - INFO - Model loaded from ./models/model.pkl
[ 2025-10-27 14:00:48,027 ] root - INFO - Data loaded from /Users/arpitgupta/Desktop/MLOPS+LLMOPS/MLOPS-LLMOPS/Datas/processed/test_preprocessed.csv
[ 2025-10-27 14:00:48,053 ] root - ERROR - Error during model evaluation: multi_class must be in ('ovo', 'ovr')
[ 2025-10-27 14:00:48,053 ] root - ERROR - Failed to complete the model evaluation process: multi_class must be in ('ovo', 'ovr')
[ 2025-10-27 14:01:47,255 ] httpx - INFO - HTTP Request: GET https://dagshub.com/api/v1/user "HTTP/1.1 200 OK"
[ 2025-10-27 14:01:47,263 ] dagshub - INFO - Accessing as thearpitgupta2003
[ 2025-10-27 14:01:48,989 ] httpx - INFO - HTTP Request: GET https://dagshub.com/api/v1/repos/thearpitgupta2003/MLOPS-LLMOPS "HTTP/1.1 200 OK"
[ 2025-10-27 14:01:50,736 ] httpx - INFO - HTTP Request: GET https://dagshub.com/api/v1/user "HTTP/1.1 200 OK"
[ 2025-10-27 14:01:50,752 ] dagshub - INFO - Initialized MLflow to track repo "thearpitgupta2003/MLOPS-LLMOPS"
[ 2025-10-27 14:01:50,753 ] dagshub - INFO - Repository thearpitgupta2003/MLOPS-LLMOPS initialized!
[ 2025-10-27 14:01:51,292 ] root - INFO - Model loaded from ./models/model.pkl
[ 2025-10-27 14:01:51,306 ] root - INFO - Data loaded from /Users/arpitgupta/Desktop/MLOPS+LLMOPS/MLOPS-LLMOPS/Datas/processed/test_preprocessed.csv
[ 2025-10-27 14:01:51,338 ] root - ERROR - Error during model evaluation: too many indices for array: array is 1-dimensional, but 2 were indexed
[ 2025-10-27 14:01:51,339 ] root - ERROR - Failed to complete the model evaluation process: too many indices for array: array is 1-dimensional, but 2 were indexed
[ 2025-10-27 14:02:37,515 ] httpx - INFO - HTTP Request: GET https://dagshub.com/api/v1/user "HTTP/1.1 200 OK"
[ 2025-10-27 14:02:37,521 ] dagshub - INFO - Accessing as thearpitgupta2003
[ 2025-10-27 14:02:39,394 ] httpx - INFO - HTTP Request: GET https://dagshub.com/api/v1/repos/thearpitgupta2003/MLOPS-LLMOPS "HTTP/1.1 200 OK"
[ 2025-10-27 14:02:41,186 ] httpx - INFO - HTTP Request: GET https://dagshub.com/api/v1/user "HTTP/1.1 200 OK"
[ 2025-10-27 14:02:41,189 ] dagshub - INFO - Initialized MLflow to track repo "thearpitgupta2003/MLOPS-LLMOPS"
[ 2025-10-27 14:02:41,189 ] dagshub - INFO - Repository thearpitgupta2003/MLOPS-LLMOPS initialized!
[ 2025-10-27 14:02:41,633 ] root - INFO - Model loaded from ./models/model.pkl
[ 2025-10-27 14:02:41,643 ] root - INFO - Data loaded from /Users/arpitgupta/Desktop/MLOPS+LLMOPS/MLOPS-LLMOPS/Datas/processed/test_preprocessed.csv
[ 2025-10-27 14:02:41,662 ] root - ERROR - Error during model evaluation: multi_class must be in ('ovo', 'ovr')
[ 2025-10-27 14:02:41,663 ] root - ERROR - Failed to complete the model evaluation process: multi_class must be in ('ovo', 'ovr')
[ 2025-10-27 14:03:44,321 ] httpx - INFO - HTTP Request: GET https://dagshub.com/api/v1/user "HTTP/1.1 200 OK"
[ 2025-10-27 14:03:44,332 ] dagshub - INFO - Accessing as thearpitgupta2003
[ 2025-10-27 14:03:45,829 ] httpx - INFO - HTTP Request: GET https://dagshub.com/api/v1/repos/thearpitgupta2003/MLOPS-LLMOPS "HTTP/1.1 200 OK"
[ 2025-10-27 14:03:48,716 ] httpx - INFO - HTTP Request: GET https://dagshub.com/api/v1/user "HTTP/1.1 200 OK"
[ 2025-10-27 14:03:48,722 ] dagshub - INFO - Initialized MLflow to track repo "thearpitgupta2003/MLOPS-LLMOPS"
[ 2025-10-27 14:03:48,723 ] dagshub - INFO - Repository thearpitgupta2003/MLOPS-LLMOPS initialized!
[ 2025-10-27 14:03:49,198 ] root - INFO - Model loaded from ./models/model.pkl
[ 2025-10-27 14:03:49,214 ] root - INFO - Data loaded from /Users/arpitgupta/Desktop/MLOPS+LLMOPS/MLOPS-LLMOPS/Datas/processed/test_preprocessed.csv
[ 2025-10-27 14:03:49,231 ] root - ERROR - Error during model evaluation: axis 1 is out of bounds for array of dimension 1
[ 2025-10-27 14:03:49,232 ] root - ERROR - Failed to complete the model evaluation process: axis 1 is out of bounds for array of dimension 1
[ 2025-10-27 14:08:30,798 ] httpx - INFO - HTTP Request: GET https://dagshub.com/api/v1/user "HTTP/1.1 200 OK"
[ 2025-10-27 14:08:30,807 ] dagshub - INFO - Accessing as thearpitgupta2003
[ 2025-10-27 14:08:32,337 ] httpx - INFO - HTTP Request: GET https://dagshub.com/api/v1/repos/thearpitgupta2003/MLOPS-LLMOPS "HTTP/1.1 200 OK"
[ 2025-10-27 14:08:34,025 ] httpx - INFO - HTTP Request: GET https://dagshub.com/api/v1/user "HTTP/1.1 200 OK"
[ 2025-10-27 14:08:34,028 ] dagshub - INFO - Initialized MLflow to track repo "thearpitgupta2003/MLOPS-LLMOPS"
[ 2025-10-27 14:08:34,029 ] dagshub - INFO - Repository thearpitgupta2003/MLOPS-LLMOPS initialized!
[ 2025-10-27 14:08:34,474 ] root - INFO - Model loaded from ./models/model.pkl
[ 2025-10-27 14:08:34,488 ] root - INFO - Data loaded from /Users/arpitgupta/Desktop/MLOPS+LLMOPS/MLOPS-LLMOPS/Datas/processed/test_preprocessed.csv
[ 2025-10-27 14:08:34,503 ] root - ERROR - Error during model evaluation: cannot access local variable 'f1_score' where it is not associated with a value
[ 2025-10-27 14:08:34,504 ] root - ERROR - Failed to complete the model evaluation process: cannot access local variable 'f1_score' where it is not associated with a value
[ 2025-10-27 14:09:24,717 ] httpx - INFO - HTTP Request: GET https://dagshub.com/api/v1/user "HTTP/1.1 200 OK"
[ 2025-10-27 14:09:24,728 ] dagshub - INFO - Accessing as thearpitgupta2003
[ 2025-10-27 14:09:26,250 ] httpx - INFO - HTTP Request: GET https://dagshub.com/api/v1/repos/thearpitgupta2003/MLOPS-LLMOPS "HTTP/1.1 200 OK"
[ 2025-10-27 14:09:28,243 ] httpx - INFO - HTTP Request: GET https://dagshub.com/api/v1/user "HTTP/1.1 200 OK"
[ 2025-10-27 14:09:28,246 ] dagshub - INFO - Initialized MLflow to track repo "thearpitgupta2003/MLOPS-LLMOPS"
[ 2025-10-27 14:09:28,247 ] dagshub - INFO - Repository thearpitgupta2003/MLOPS-LLMOPS initialized!
[ 2025-10-27 14:09:28,678 ] root - INFO - Model loaded from ./models/model.pkl
[ 2025-10-27 14:09:28,689 ] root - INFO - Data loaded from /Users/arpitgupta/Desktop/MLOPS+LLMOPS/MLOPS-LLMOPS/Datas/processed/test_preprocessed.csv
[ 2025-10-27 14:09:28,704 ] root - ERROR - Error during model evaluation: cannot access local variable 'f1_score' where it is not associated with a value
[ 2025-10-27 14:09:28,704 ] root - ERROR - Failed to complete the model evaluation process: cannot access local variable 'f1_score' where it is not associated with a value
[ 2025-10-27 14:09:56,565 ] httpx - INFO - HTTP Request: GET https://dagshub.com/api/v1/user "HTTP/1.1 200 OK"
[ 2025-10-27 14:09:56,575 ] dagshub - INFO - Accessing as thearpitgupta2003
[ 2025-10-27 14:09:57,874 ] httpx - INFO - HTTP Request: GET https://dagshub.com/api/v1/repos/thearpitgupta2003/MLOPS-LLMOPS "HTTP/1.1 200 OK"
[ 2025-10-27 14:09:59,175 ] httpx - INFO - HTTP Request: GET https://dagshub.com/api/v1/user "HTTP/1.1 200 OK"
[ 2025-10-27 14:09:59,181 ] dagshub - INFO - Initialized MLflow to track repo "thearpitgupta2003/MLOPS-LLMOPS"
[ 2025-10-27 14:09:59,182 ] dagshub - INFO - Repository thearpitgupta2003/MLOPS-LLMOPS initialized!
[ 2025-10-27 14:09:59,583 ] root - INFO - Model loaded from ./models/model.pkl
[ 2025-10-27 14:09:59,592 ] root - INFO - Data loaded from /Users/arpitgupta/Desktop/MLOPS+LLMOPS/MLOPS-LLMOPS/Datas/processed/test_preprocessed.csv
[ 2025-10-27 14:09:59,606 ] root - INFO - Model evaluation metrics calculated
[ 2025-10-27 14:09:59,606 ] root - INFO - Metrics saved to reports/metrics.json
[ 2025-10-27 14:09:59,608 ] root - ERROR - Failed to complete the model evaluation process: float() argument must be a string or a real number, not 'tuple'
[ 2025-10-27 14:11:25,822 ] httpx - INFO - HTTP Request: GET https://dagshub.com/api/v1/user "HTTP/1.1 200 OK"
[ 2025-10-27 14:11:25,833 ] dagshub - INFO - Accessing as thearpitgupta2003
[ 2025-10-27 14:11:27,392 ] httpx - INFO - HTTP Request: GET https://dagshub.com/api/v1/repos/thearpitgupta2003/MLOPS-LLMOPS "HTTP/1.1 200 OK"
[ 2025-10-27 14:11:31,863 ] httpx - INFO - HTTP Request: GET https://dagshub.com/api/v1/user "HTTP/1.1 200 OK"
[ 2025-10-27 14:11:31,867 ] dagshub - INFO - Initialized MLflow to track repo "thearpitgupta2003/MLOPS-LLMOPS"
[ 2025-10-27 14:11:31,868 ] dagshub - INFO - Repository thearpitgupta2003/MLOPS-LLMOPS initialized!
[ 2025-10-27 14:11:32,283 ] root - INFO - Model loaded from ./models/model.pkl
[ 2025-10-27 14:11:32,289 ] root - INFO - Data loaded from /Users/arpitgupta/Desktop/MLOPS+LLMOPS/MLOPS-LLMOPS/Datas/processed/test_preprocessed.csv
[ 2025-10-27 14:11:32,303 ] root - INFO - Model evaluation metrics calculated
[ 2025-10-27 14:11:32,304 ] root - INFO - Metrics saved to reports/metrics.json
[ 2025-10-27 16:51:50,153 ] dotenv.main - WARNING - Python-dotenv could not parse statement starting at line 1
[ 2025-10-27 16:51:50,153 ] dotenv.main - WARNING - Python-dotenv could not parse statement starting at line 2
[ 2025-10-27 16:51:50,153 ] dotenv.main - WARNING - Python-dotenv could not parse statement starting at line 3
[ 2025-10-27 16:51:50,153 ] dotenv.main - WARNING - Python-dotenv could not parse statement starting at line 5
[ 2025-10-27 16:51:50,153 ] dotenv.main - WARNING - Python-dotenv could not parse statement starting at line 6
[ 2025-10-27 16:51:50,153 ] dotenv.main - WARNING - Python-dotenv could not parse statement starting at line 7
[ 2025-10-27 16:51:51,863 ] httpx - INFO - HTTP Request: GET https://dagshub.com/api/v1/user "HTTP/1.1 200 OK"
[ 2025-10-27 16:51:51,874 ] dagshub - INFO - Accessing as thearpitgupta2003
[ 2025-10-27 16:51:53,372 ] httpx - INFO - HTTP Request: GET https://dagshub.com/api/v1/repos/thearpitgupta2003/MLOPS-LLMOPS "HTTP/1.1 200 OK"
[ 2025-10-27 16:51:55,221 ] httpx - INFO - HTTP Request: GET https://dagshub.com/api/v1/user "HTTP/1.1 200 OK"
[ 2025-10-27 16:51:55,225 ] dagshub - INFO - Initialized MLflow to track repo "thearpitgupta2003/MLOPS-LLMOPS"
[ 2025-10-27 16:51:55,225 ] dagshub - INFO - Repository thearpitgupta2003/MLOPS-LLMOPS initialized!
[ 2025-10-27 16:51:56,698 ] root - INFO - runs:/06b2592b99254e718b520a4053c906bc/model
[ 2025-10-27 16:53:06,274 ] root - ERROR - Error during model and transformer registration: API request to https://dagshub.com/thearpitgupta2003/MLOPS-LLMOPS.mlflow/api/2.0/mlflow/runs/get failed with exception HTTPSConnectionPool(host='dagshub.com', port=443): Max retries exceeded with url: /thearpitgupta2003/MLOPS-LLMOPS.mlflow/api/2.0/mlflow/runs/get?run_uuid=06b2592b99254e718b520a4053c906bc&run_id=06b2592b99254e718b520a4053c906bc (Caused by ResponseError('too many 500 error responses'))
[ 2025-10-27 16:53:06,279 ] root - ERROR - Failed to complete the model registration process: API request to https://dagshub.com/thearpitgupta2003/MLOPS-LLMOPS.mlflow/api/2.0/mlflow/runs/get failed with exception HTTPSConnectionPool(host='dagshub.com', port=443): Max retries exceeded with url: /thearpitgupta2003/MLOPS-LLMOPS.mlflow/api/2.0/mlflow/runs/get?run_uuid=06b2592b99254e718b520a4053c906bc&run_id=06b2592b99254e718b520a4053c906bc (Caused by ResponseError('too many 500 error responses'))
[ 2025-10-27 16:53:31,086 ] dotenv.main - WARNING - Python-dotenv could not parse statement starting at line 1
[ 2025-10-27 16:53:31,086 ] dotenv.main - WARNING - Python-dotenv could not parse statement starting at line 2
[ 2025-10-27 16:53:31,086 ] dotenv.main - WARNING - Python-dotenv could not parse statement starting at line 3
[ 2025-10-27 16:53:31,086 ] dotenv.main - WARNING - Python-dotenv could not parse statement starting at line 5
[ 2025-10-27 16:53:31,087 ] dotenv.main - WARNING - Python-dotenv could not parse statement starting at line 6
[ 2025-10-27 16:53:31,087 ] dotenv.main - WARNING - Python-dotenv could not parse statement starting at line 7
[ 2025-10-27 16:53:32,205 ] httpx - INFO - HTTP Request: GET https://dagshub.com/api/v1/user "HTTP/1.1 200 OK"
[ 2025-10-27 16:53:32,212 ] dagshub - INFO - Accessing as thearpitgupta2003
[ 2025-10-27 16:53:33,624 ] httpx - INFO - HTTP Request: GET https://dagshub.com/api/v1/repos/thearpitgupta2003/MLOPS-LLMOPS "HTTP/1.1 200 OK"
[ 2025-10-27 16:53:35,470 ] httpx - INFO - HTTP Request: GET https://dagshub.com/api/v1/user "HTTP/1.1 200 OK"
[ 2025-10-27 16:53:35,472 ] dagshub - INFO - Initialized MLflow to track repo "thearpitgupta2003/MLOPS-LLMOPS"
[ 2025-10-27 16:53:35,473 ] dagshub - INFO - Repository thearpitgupta2003/MLOPS-LLMOPS initialized!
[ 2025-10-27 16:53:37,098 ] root - INFO - runs:/06b2592b99254e718b520a4053c906bc/model
[ 2025-10-27 16:54:46,668 ] root - ERROR - Error during model and transformer registration: API request to https://dagshub.com/thearpitgupta2003/MLOPS-LLMOPS.mlflow/api/2.0/mlflow/runs/get failed with exception HTTPSConnectionPool(host='dagshub.com', port=443): Max retries exceeded with url: /thearpitgupta2003/MLOPS-LLMOPS.mlflow/api/2.0/mlflow/runs/get?run_uuid=06b2592b99254e718b520a4053c906bc&run_id=06b2592b99254e718b520a4053c906bc (Caused by ResponseError('too many 500 error responses'))
[ 2025-10-27 16:54:46,673 ] root - ERROR - Failed to complete the model registration process: API request to https://dagshub.com/thearpitgupta2003/MLOPS-LLMOPS.mlflow/api/2.0/mlflow/runs/get failed with exception HTTPSConnectionPool(host='dagshub.com', port=443): Max retries exceeded with url: /thearpitgupta2003/MLOPS-LLMOPS.mlflow/api/2.0/mlflow/runs/get?run_uuid=06b2592b99254e718b520a4053c906bc&run_id=06b2592b99254e718b520a4053c906bc (Caused by ResponseError('too many 500 error responses'))
[ 2025-10-27 17:27:00,876 ] root - INFO - Data saved to ./Datas/raw
[ 2025-10-27 17:28:00,600 ] root - INFO - Data saved to ./Datas/raw
[ 2025-10-27 17:28:02,125 ] root - ERROR - Failed to complete the data preprocessing process: [Errno 2] No such file or directory: '/Users/arpitgupta/Desktop/MLOPS+LLMOPS/MLOPS-LLMOPS/Datas/raw/Crop_recommendation.csv'
[ 2025-10-27 17:42:00,656 ] root - ERROR - Failed to complete the data preprocessing process: [Errno 2] No such file or directory: '/Users/arpitgupta/Desktop/MLOPS+LLMOPS/MLOPS-LLMOPS/Datas/raw/Crop_recommendation.csv'
[ 2025-10-29 13:05:05,242 ] root - ERROR - Failed to complete the data preprocessing process: [Errno 2] No such file or directory: '/Users/arpitgupta/Desktop/MLOPS+LLMOPS/MLOPS-LLMOPS/Datas/raw/Crop_recommendation.csv'
[ 2025-10-29 13:05:28,580 ] root - INFO - Raw data loaded successfully
[ 2025-10-29 13:05:28,580 ] root - INFO - preprocessing the data 
[ 2025-10-29 13:05:28,580 ] root - INFO - Starting the preprocessing Step
[ 2025-10-29 13:05:28,585 ] root - INFO - Starting up with the train test split 
[ 2025-10-29 13:05:28,587 ] root - INFO - Done with the splitting 
[ 2025-10-29 13:05:28,587 ] root - INFO - Starting with the scaling 
[ 2025-10-29 13:05:28,590 ] root - INFO - Done with the scailing  
[ 2025-10-29 13:05:28,590 ] root - INFO - X_train_scaled shape : (1760, 7) and X_test_scaled (1760, 7)
[ 2025-10-29 13:05:28,591 ] root - INFO - Converting the trained array into dataframe
[ 2025-10-29 13:05:28,591 ] root - INFO - Converting the test array into dataframe
[ 2025-10-29 13:05:28,591 ] root - INFO - 
Preprocessing completed successfully!
[ 2025-10-29 13:05:28,592 ] root - INFO - saving the preprocessing csv's 
[ 2025-10-29 13:05:28,593 ] root - ERROR - Failed to complete the data preprocessing process: Cannot save file into a non-existent directory: '/Users/arpitgupta/Desktop/MLOPS+LLMOPS/MLOPS-LLMOPS/Datas/processed'
[ 2025-10-29 13:05:54,286 ] root - INFO - Raw data loaded successfully
[ 2025-10-29 13:05:54,286 ] root - INFO - preprocessing the data 
[ 2025-10-29 13:05:54,286 ] root - INFO - Starting the preprocessing Step
[ 2025-10-29 13:05:54,288 ] root - INFO - Starting up with the train test split 
[ 2025-10-29 13:05:54,288 ] root - INFO - Done with the splitting 
[ 2025-10-29 13:05:54,289 ] root - INFO - Starting with the scaling 
[ 2025-10-29 13:05:54,291 ] root - INFO - Done with the scailing  
[ 2025-10-29 13:05:54,291 ] root - INFO - X_train_scaled shape : (1760, 7) and X_test_scaled (1760, 7)
[ 2025-10-29 13:05:54,291 ] root - INFO - Converting the trained array into dataframe
[ 2025-10-29 13:05:54,291 ] root - INFO - Converting the test array into dataframe
[ 2025-10-29 13:05:54,292 ] root - INFO - 
Preprocessing completed successfully!
[ 2025-10-29 13:05:54,292 ] root - INFO - saving the preprocessing csv's 
[ 2025-10-29 13:05:54,317 ] root - INFO - Processed train and test data saved successfully in /Users/arpitgupta/Desktop/MLOPS+LLMOPS/MLOPS-LLMOPS/Datas/processed
